spring:
   datasource:
       url: jdbc:mysql://127.0.0.1:3306/zhou?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
       username: root
       password: 1234
   jpa:
#自动生产数据库的表，DDL表示数据定义语言，通常用来管理表结构的
       generate-ddl: true
#运行时自动生成的SQL语句打印出来
       show-sql: true     
   redis:
       host: 120.78.127.155
       port: 6379
       database: 10 
   # useSSL=false  表示不使用加密通讯，本机的数据库没有必要加密
   # serverTimezone=CST 表示指定服务器的时区，CST=China Standard Time
